module.exports={
  server:{
    //后台服务器占用端口
    port:'3000',
    //mongodb数据库信息,必填
    database:{
      host:'',
      port:'27017',
      database:'',
      name:'',
      pwd:''
    },
    user:{
      //密码加密密匙，和加密次数
      salt:'salt',
      saltTimes:2,
      //初始管理员
      admin:{
        username:'root',
        password:'12345678',
        email:'8888@qq.com',
        role:'amdin'
      }
    },
    session:{
      //session加密字符串
      secret:'secret key',
      cookie:{
        maxAge:24*60*60*1000
      }
    },
    //用于发送验证码的邮箱,需要先向qq邮箱官网开启POP3/SMTP/IMAP，必填
    email:{
      service:'QQ',
      user:'',
      pass: '',
    }
  },
  page:{
    port:'3001',
    home:{
      title:'root的个人博客',
      banner:'/img/banner.jpg',
      card_bg:'/img/card_bg.jpg',
      avatar_pic:'/img/avatar_pic.jpg',
      copyright:'©2021 root',
       //备案信息，可不填
       icp:''
    }
  }
}

